addons:
  sonarcloud:
    organization: "theghostshell"
    token: $SONAR_TOKEN

dist: xenial
language: java
jdk:
- openjdk8
script:
- "./gradlew assemble"
- "./gradlew check"
- "./gradlew codeCoverageReport"
- "./gradlew jacocoTestReport"
- "sonar-scanner -X"
#- "./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=Evergarden"
after_success:
- bash <(curl -s https://codecov.io/bash) -f "*.xml" -s "./build"